"""CSV tables: points, drillholes, structural data, block models."""
import sys, unittest, tempfile, os
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'pipelines'))

import io

from geomodel.model import BlockModel, PointSet, NAN
from geomodel.formats import tables


def isnan(v):
    return isinstance(v, float) and v != v


class TempDirMixin(object):
    def setUp(self):
        self.tmp = tempfile.mkdtemp(prefix='nwmm-tables-')

    def path(self, name):
        return os.path.join(self.tmp, name)

    def write(self, name, text):
        p = self.path(name)
        with open(p, 'w', encoding='utf-8', newline='') as fh:
            fh.write(text)
        return p


# --------------------------------------------------------------------- helpers
class TestHelpers(unittest.TestCase):
    def test_norm_and_find(self):
        self.assertEqual(tables.norm('Hole_ID'), 'holeid')
        self.assertEqual(tables.norm(' Dip Azimuth (deg)'), 'dipazimuthdeg')
        t = tables.parse_table(b'Easting,NORTH,RL,Au ppm\n1,2,3,4\n')
        self.assertEqual(t.find(tables.X_SYN), 'Easting')
        self.assertEqual(t.find(tables.Y_SYN), 'NORTH')
        self.assertEqual(t.find(tables.Z_SYN), 'RL')
        self.assertEqual(t.find(('x',), explicit='au_ppm'), 'Au ppm')
        self.assertIsNone(t.find(('nothing',)))
        with self.assertRaises(KeyError):
            t.find(('x',), explicit='missing')

    def test_delimiter_sniffing(self):
        for text in ('x,y,z\n1,2,3\n', 'x;y;z\n1;2;3\n', 'x\ty\tz\n1\t2\t3\n', 'x|y|z\n1|2|3\n', 'x y z\n1 2 3\n'):
            t = tables.parse_table(text.encode())
            self.assertEqual(t.headers, ['x', 'y', 'z'], text)
            self.assertEqual(t.columns['z'], ['3'], text)

    def test_preamble_and_bom(self):
        t = tables.parse_table('﻿# generated by test\n# block_size: 10, 10, 5\nname: demo\nx,y\n1,2\n'.encode('utf-8'))
        self.assertEqual(t.headers, ['x', 'y'])
        self.assertEqual(t.preamble['block_size'], '10, 10, 5')
        self.assertEqual(t.preamble['name'], 'demo')
        self.assertEqual(t.n, 1)

    def test_ragged_and_blank_rows(self):
        t = tables.parse_table(b'a,b,c\n1,2\n\n3,4,5,6\n')
        self.assertEqual(t.n, 2)
        self.assertEqual(t.columns['c'], ['', '5'])
        self.assertTrue(any('different number' in w for w in t.warnings))


# ---------------------------------------------------------------------- points
class TestPoints(TempDirMixin, unittest.TestCase):
    def test_read_synonyms_types_and_blanks(self):
        ps = tables.read_points_csv(b'Easting;Northing;RL;Au_ppm;Lith\n500000;4000000;1200.5;0.5;qtz\n500010;4000010;1201;;sch\n')
        self.assertEqual(ps.kind, 'points')
        self.assertEqual(ps.n, 2)
        self.assertEqual(ps.point(0), (500000.0, 4000000.0, 1200.5))
        self.assertEqual(ps.attributes['Au_ppm'], [0.5, None])
        self.assertEqual(ps.attributes['Lith'], ['qtz', 'sch'])
        self.assertEqual(list(ps.attributes), ['Au_ppm', 'Lith'])                # file column order kept
        self.assertEqual(ps.metadata['columns'], {'x': 'Easting', 'y': 'Northing', 'z': 'RL'})
        self.assertEqual(ps.metadata['warnings'], [])
        self.assertEqual(ps.provenance['format'], 'csv_points')

    def test_no_z_and_explicit_columns(self):
        ps = tables.read_points_csv(b'X,Y,name\n1,2,a\n3,4,b\n')
        self.assertEqual(list(ps.xyz), [1.0, 2.0, 0.0, 3.0, 4.0, 0.0])
        self.assertTrue(any('Z set to 0' in w for w in ps.metadata['warnings']))
        ps = tables.read_points_csv(b'lon,lat,h,v\n1,2,3,4\n', x='lon', y='lat', z='h')
        self.assertEqual(ps.point(0), (1.0, 2.0, 3.0))
        self.assertEqual(list(ps.attributes), ['v'])
        with self.assertRaises(ValueError):
            tables.read_points_csv(b'a,b\n1,2\n')

    def test_write_and_round_trip(self):
        ps = PointSet(name='pts', attributes={'au': [], 'lith': []})     # ordered columns
        ps.add(1, 2, 3, au=0.5, lith='qtz')
        ps.add(4, 5, 6, au=None, lith='sch')
        text = tables.write_points_csv(ps, io.BytesIO()).decode()
        self.assertEqual(text.splitlines()[0], 'x,y,z,au,lith')
        self.assertEqual(text.splitlines()[2], '4,5,6,,sch')
        lf = tables.write_points_csv(ps, io.BytesIO(), leapfrog=True, columns=['lith']).decode()
        self.assertEqual(lf.splitlines()[0], 'East,North,Elev,lith')
        p = tables.write_points_csv(ps, self.path('pts.csv'))
        r = tables.read_points_csv(p)
        self.assertEqual(list(r.xyz), list(ps.xyz))
        self.assertEqual(r.attributes['au'], [0.5, None])
        self.assertEqual(r.attributes['lith'], ['qtz', 'sch'])
        self.assertEqual(r.name, 'pts')
        r2 = tables.read_points_csv(lf.encode())
        self.assertEqual(r2.point(1), (4.0, 5.0, 6.0))


# ------------------------------------------------------------------ drillholes
COLLAR = 'HOLE_ID,EAST,NORTH,ELEV,EOH,Prospect\nDH1,1000,2000,300,100,North\nDH2,1050,2000,305,50,North\n'
SURVEY_NEG = 'holeid,depth,azimuth,dip\nDH1,0,90,-60\nDH1,50,95,-58\nDH1,100,100,-55\nDH2,0,0,-90\n'
ASSAY = 'holeid,from,to,Au,Cu_pct,comment\nDH1,0,10,0.5,0.1,ok\nDH1,10,20,1.5,,high\nDH2,0,5,0.1,0.2,\n'
LITH = 'BHID,Depth_From,Depth_To,Lith\nDH1,0,15,GRN\nDH1,15,100,SCH\nDH9,0,1,XX\n'


class TestDrillholes(TempDirMixin, unittest.TestCase):
    def test_deviated_hole_negative_dip_down(self):
        c = self.write('collar.csv', COLLAR)
        s = self.write('survey.csv', SURVEY_NEG)
        a = self.write('assay.csv', ASSAY)
        l = self.write('lith.csv', LITH)
        dh = tables.read_drillholes(c, s, {'assay': a, 'lith': l}, negative_dip_down=True)
        self.assertEqual(dh.kind, 'drillholes')
        self.assertEqual(dh.holes(), ['DH1', 'DH2'])
        self.assertEqual(dh.collars[0], {'hole': 'DH1', 'x': 1000.0, 'y': 2000.0, 'z': 300.0, 'depth': 100.0, 'Prospect': 'North'})
        self.assertEqual([sv['dip'] for sv in dh.surveys], [60.0, 58.0, 55.0, 90.0])     # positive down
        self.assertEqual(dh.surveys[1], {'hole': 'DH1', 'depth': 50.0, 'azimuth': 95.0, 'dip': 58.0})
        self.assertEqual(dh.intervals['assay'][1], {'hole': 'DH1', 'from': 10.0, 'to': 20.0, 'Au': 1.5, 'Cu_pct': None, 'comment': 'high'})
        self.assertEqual(dh.intervals['lith'][0], {'hole': 'DH1', 'from': 0.0, 'to': 15.0, 'Lith': 'GRN'})
        self.assertTrue(any('lith' in w and 'DH9' in w for w in dh.metadata['warnings']))
        self.assertEqual(dh.metadata['dip_convention'], 'positive down')
        self.assertEqual(dh.provenance['format'], 'csv_drillholes')
        self.assertEqual(dh.provenance['path'], c)
        # desurvey: DH1 heads east and down, ends at 100 m; DH2 is vertical
        tr = dh.desurvey()
        d, x, y, z = tr['DH1'][-1]
        self.assertAlmostEqual(d, 100.0)
        self.assertGreater(x, 1040.0)
        self.assertLess(y, 2000.0)
        self.assertLess(z, 300.0 - 80.0)
        self.assertGreater(z, 300.0 - 90.0)
        self.assertEqual([round(v, 6) for v in tr['DH2'][-1]], [50.0, 1050.0, 2000.0, 255.0])

    def test_dip_sign_warning_without_flag(self):
        c = self.write('collar.csv', COLLAR)
        s = self.write('survey.csv', SURVEY_NEG)
        dh = tables.read_drillholes(c, s)
        self.assertEqual([sv['dip'] for sv in dh.surveys], [-60.0, -58.0, -55.0, -90.0])
        self.assertTrue(any('negative_dip_down=True' in w for w in dh.metadata['warnings']))
        dh2 = tables.read_drillholes(c)
        self.assertEqual(dh2.surveys, [])
        self.assertTrue(any('vertical' in w for w in dh2.metadata['warnings']))
        self.assertEqual(dh2.desurvey()['DH1'][-1][3], 200.0)

    def test_bytes_sources_and_missing_columns(self):
        dh = tables.read_drillholes(COLLAR.encode(), SURVEY_NEG.encode(), {'assay': ASSAY.encode()})
        self.assertEqual(len(dh.intervals['assay']), 3)
        self.assertIsNone(dh.provenance['path'])
        with self.assertRaises(ValueError):
            tables.read_drillholes(b'a,b,c\n1,2,3\n')
        with self.assertRaises(ValueError):
            tables.read_drillholes(COLLAR.encode(), b'holeid,depth\nDH1,0\n')
        with self.assertRaises(ValueError):
            tables.read_drillholes(COLLAR.encode(), None, {'x': b'holeid,from,val\nDH1,0,1\n'})

    def test_write_and_round_trip(self):
        c = self.write('collar.csv', COLLAR)
        s = self.write('survey.csv', SURVEY_NEG)
        a = self.write('assay.csv', ASSAY)
        dh = tables.read_drillholes(c, s, {'assay': a}, negative_dip_down=True)
        out = tables.write_drillholes(dh, self.path('out') + os.sep)
        self.assertEqual(sorted(out), ['assay', 'collar', 'survey'])
        self.assertEqual(Path(out['collar']).read_text().splitlines()[0], 'holeid,x,y,z,max_depth,Prospect')
        self.assertEqual(Path(out['survey']).read_text().splitlines()[0:2], ['holeid,depth,azimuth,dip', 'DH1,0,90,60'])
        self.assertEqual(Path(out['assay']).read_text().splitlines()[0], 'holeid,from,to,Au,Cu_pct,comment')
        dh2 = tables.read_drillholes(out['collar'], out['survey'], {'assay': out['assay']})
        self.assertEqual(dh2.collars, dh.collars)
        self.assertEqual(dh2.surveys, dh.surveys)
        self.assertEqual(dh2.intervals, dh.intervals)
        self.assertEqual(dh2.metadata['warnings'], [])
        out2 = tables.write_drillholes(dh, self.path('prefix'))
        self.assertTrue(out2['collar'].endswith('prefix_collar.csv'))
        self.assertTrue(os.path.exists(out2['survey']))


# ------------------------------------------------------------------ structural
class TestStructural(TempDirMixin, unittest.TestCase):
    def test_strike_to_dip_azimuth_and_polarity(self):
        ps = tables.read_structural_csv(b'x,y,z,strike,dip,polarity,station\n1,2,3,45,30,1,S1\n4,5,6,300,80,,S2\n')
        self.assertEqual(ps.role, 'structural')
        self.assertEqual(ps.n, 2)
        self.assertEqual(ps.attributes['dip'], [30.0, 80.0])
        self.assertEqual(ps.attributes['dip_azimuth'], [135.0, 30.0])         # strike + 90, wrapped
        self.assertEqual(ps.attributes['polarity'], [1.0, None])
        self.assertEqual(ps.attributes['station'], ['S1', 'S2'])
        self.assertEqual(list(ps.attributes), ['dip', 'dip_azimuth', 'polarity', 'station'])
        self.assertTrue(any('right-hand rule' in w for w in ps.metadata['warnings']))
        self.assertEqual(ps.provenance['format'], 'csv_structural')

    def test_dip_direction_synonyms(self):
        for hdr in ('Dip Direction', 'dipdir', 'DIP_AZIMUTH', 'azimuth'):
            ps = tables.read_structural_csv(('East,North,Elev,%s,Dip\n1,2,3,135,30\n' % hdr).encode())
            self.assertEqual(ps.attributes['dip_azimuth'], [135.0], hdr)
            self.assertEqual(ps.attributes['dip'], [30.0], hdr)
            self.assertNotIn('polarity', ps.attributes)
        ps = tables.read_structural_csv(b'x,y,z,dip_direction,strike,dip\n1,2,3,135,45,30\n')
        self.assertEqual(ps.attributes['dip_azimuth'], [135.0])                  # explicit column wins
        with self.assertRaises(ValueError):
            tables.read_structural_csv(b'x,y,z,value\n1,2,3,4\n')

    def test_write_and_round_trip(self):
        ps = tables.read_structural_csv(b'x,y,z,strike,dip,polarity\n1,2,3,45,30,1\n4,5,6,300,80,\n')
        text = tables.write_structural_csv(ps, io.BytesIO()).decode()
        lines = text.splitlines()
        self.assertEqual(lines[0], 'x,y,z,dip,dip_azimuth,polarity')
        self.assertEqual(lines[1], '1,2,3,30,135,1')
        self.assertEqual(lines[2], '4,5,6,80,30,')
        p = tables.write_structural_csv(ps, self.path('st.csv'))
        r = tables.read_structural_csv(p)
        self.assertEqual(r.attributes['dip'], ps.attributes['dip'])
        self.assertEqual(r.attributes['dip_azimuth'], ps.attributes['dip_azimuth'])
        self.assertEqual(r.attributes['polarity'], [1.0, None])
        self.assertEqual(r.metadata['warnings'], [])


# ------------------------------------------------------------------ block model
def sample_bm():
    bm = BlockModel([1000, 2000, 100], [10, 10, 5], [3, 2, 2], name='bm')
    au = [float(i) for i in range(bm.n)]
    au[0] = NAN
    au[bm.n - 1] = NAN                     # two empty corner blocks
    bm.add_attribute('au', au)
    bm.add_attribute('rock', ['ox' if i % 2 else '' for i in range(bm.n)], kind='text')
    return bm


class TestBlockModel(TempDirMixin, unittest.TestCase):
    def test_write_embedded_header_sidecar_and_round_trip(self):
        bm = sample_bm()
        p = tables.write_blockmodel_csv(bm, self.path('bm.csv'))
        text = Path(p).read_text()
        lines = text.splitlines()
        self.assertTrue(lines[0].startswith('# name: bm'))
        self.assertIn('# base_point: 1000, 2000, 100', lines)
        self.assertIn('# block_size: 10, 10, 5', lines)
        self.assertIn('# count: 3, 2, 2', lines)
        self.assertIn('# azimuth: 0', lines)
        hdr = [ln for ln in lines if not ln.startswith('#')][0]
        self.assertEqual(hdr, 'x,y,z,dx,dy,dz,au,rock')
        rows = [ln for ln in lines if not ln.startswith('#')][1:]
        self.assertEqual(len(rows), bm.n - 1)                 # block 0 is all-empty (NaN + ''), skipped; last has rock
        self.assertEqual(rows[0], '1015,2005,102.5,10,10,5,1,ox')
        side = Path(p + '.txt')
        self.assertTrue(side.exists())
        self.assertIn('block_size: 10, 10, 5\n', side.read_text())
        self.assertIn('count: 3, 2, 2\n', side.read_text())
        self.assertIn('rows: %d\n' % (bm.n - 1), side.read_text())
        r = tables.read_blockmodel_csv(p)
        self.assertEqual(r.origin, [1000.0, 2000.0, 100.0])
        self.assertEqual(r.block_size, [10.0, 10.0, 5.0])
        self.assertEqual(r.count, [3, 2, 2])
        self.assertEqual(r.metadata['block_size_source'], 'embedded header')
        self.assertEqual(r.metadata['header']['name'], 'bm')
        a, b = bm.attributes['au']['values'], r.attributes['au']['values']
        self.assertEqual(len(b), bm.n)
        for x, y in zip(a, b):
            self.assertTrue((isnan(x) and isnan(y)) or x == y)
        self.assertEqual(r.attributes['rock']['type'], 'text')
        self.assertEqual(r.attributes['rock']['values'][:3], [None, 'ox', ''])
        self.assertTrue(any('no row' in w for w in r.metadata['warnings']))
        # keep empties
        full = tables.write_blockmodel_csv(bm, io.BytesIO(), skip_empty=False, embedded_header=False).decode()
        self.assertEqual(len(full.splitlines()), bm.n + 1)
        self.assertTrue(full.startswith('x,y,z,dx,dy,dz,au,rock'))
        only_au = tables.write_blockmodel_csv(bm, io.BytesIO(), attributes=['au'], embedded_header=False).decode()
        self.assertEqual(only_au.splitlines()[0], 'x,y,z,dx,dy,dz,au')
        self.assertEqual(len(only_au.splitlines()), bm.n - 2 + 1)

    def test_no_header_sizes_from_columns_and_inferred(self):
        bm = sample_bm()
        data = tables.write_blockmodel_csv(bm, io.BytesIO(), embedded_header=False, skip_empty=False).decode()
        r = tables.read_blockmodel_csv(data.encode())
        self.assertEqual(r.metadata['block_size_source'], 'size columns')
        self.assertEqual((r.origin, r.block_size, r.count), ([1000.0, 2000.0, 100.0], [10.0, 10.0, 5.0], [3, 2, 2]))
        # centroid-only table, one interior block missing, Leapfrog-ish headers
        rows = ['XC,YC,ZC,au']
        for i in range(bm.n):
            if i == 4:
                continue
            x, y, z = bm.centroid(*bm.ijk(i))
            rows.append('%g,%g,%g,%d' % (x, y, z, i))
        r = tables.read_blockmodel_csv('\n'.join(rows).encode())
        self.assertEqual(r.metadata['block_size_source'], 'inferred from centroid spacing')
        self.assertEqual((r.origin, r.block_size, r.count), ([1000.0, 2000.0, 100.0], [10.0, 10.0, 5.0], [3, 2, 2]))
        vals = r.attributes['au']['values']
        self.assertTrue(isnan(vals[4]))
        self.assertEqual(vals[5], 5.0)
        self.assertTrue(any('1 of 12' in w for w in r.metadata['warnings']))
        r2 = tables.read_blockmodel_csv('\n'.join(rows).encode(), block_size=(10, 10, 5))
        self.assertEqual(r2.metadata['block_size_source'], 'argument')
        self.assertEqual(r2.count, [3, 2, 2])

    def test_off_lattice_rows_and_duplicates(self):
        r = tables.read_blockmodel_csv(b'x,y,z,dx,dy,dz,au\n5,5,2.5,10,10,5,1\n15,5,2.5,10,10,5,2\n12,5,2.5,10,10,5,3\n15,5,2.5,10,10,5,9\n')
        self.assertEqual(r.count, [2, 1, 1])
        self.assertEqual(list(r.attributes['au']['values']), [1.0, 9.0])
        self.assertTrue(any('do not land' in w for w in r.metadata['warnings']))
        self.assertTrue(any('duplicate' in w for w in r.metadata['warnings']))
        with self.assertRaises(ValueError):
            tables.read_blockmodel_csv(b'a,b,c\n1,2,3\n')

    def test_rotated_model_round_trip(self):
        bm = BlockModel([1000, 2000, 100], [10, 10, 5], [3, 2, 1], azimuth=30, name='rot')
        bm.add_attribute('v', list(range(bm.n)))
        data = tables.write_blockmodel_csv(bm, io.BytesIO(), sidecar=False)
        r = tables.read_blockmodel_csv(data)
        self.assertEqual(r.azimuth, 30.0)
        self.assertEqual(r.origin, [1000.0, 2000.0, 100.0])
        self.assertEqual(r.count, [3, 2, 1])
        self.assertEqual(list(r.attributes['v']['values']), [0.0, 1.0, 2.0, 3.0, 4.0, 5.0])
        self.assertEqual(r.metadata['warnings'], [])
        for i in range(bm.n):
            self.assertEqual([round(v, 6) for v in r.centroid(*r.ijk(i))], [round(v, 6) for v in bm.centroid(*bm.ijk(i))])

    def test_leapfrog_style_header_lines(self):
        text = ('# Block model exported from somewhere\n'
                'Model name: Demo\n'
                'x,y,z,dx,dy,dz,grade\n'
                '5,5,2.5,10,10,5,1.5\n'
                '15,5,2.5,10,10,5,2.5\n')
        r = tables.read_blockmodel_csv(text.encode())
        self.assertEqual(r.metadata['header']['Model name'], 'Demo')
        self.assertEqual(r.count, [2, 1, 1])
        self.assertEqual(list(r.attributes['grade']['values']), [1.5, 2.5])


if __name__ == '__main__':
    unittest.main()
